### ISSUE TITLE
Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies

### ISSUE THREAD

**Issue by StigTech** [Anathena/Anathena#261]
The line of code below utilized in a .Net Standard 2.0 class library, called by a standard WPF desktop app using .Net Framework 4.6.2 (also tried 4.7.1 and 4.6.1)

` Dim valueCollectorTask As TrackableTask(Of Snapshot) = ValueCollector.CollectValues(SnapshotManager.GetSnapshot(snapshot.SnapshotRetrievalMode.FromActiveSnapshotOrPrefilter, dataType))`

Results in this exception exception below at runtime. There are no issues compiling, only at runtime.

**System.IO.FileNotFoundException**
  HResult=0x80070002
  Message=**Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0,** Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=Squalr.Engine
  StackTrace:
   at Squalr.Engine.OS.Vectors.get_VectorSize()
   at Squalr.Engine.Scanning.Snapshots.ReadGroup..ctor(UInt64 baseAddress, Int32 regionSize, DataType dataType, Int32 alignment)
   at Squalr.Engine.Scanning.Snapshots.SnapshotManager.CreateSnapshotFromSettings(DataType dataType)
   at Squalr.Engine.Scanning.Snapshots.SnapshotManager.GetSnapshot(SnapshotRetrievalMode snapshotCreationMode, DataType dataType)
   at Squalr.Source.Prefilters.Prefilter.GetPrefilteredSnapshot(DataType dataType)
   at Squalr.Engine.Scanning.Snapshots.SnapshotManager.GetActiveSnapshotCreateIfNone(DataType dataType)
   at Squalr.Engine.Scanning.Snapshots.SnapshotManager.GetSnapshot(SnapshotRetrievalMode snapshotCreationMode, DataType dataType)

**Comment by zcanann** [comment]
I havent quite figured this out, but a reference to this library needs to be added to the WPF app -- just add it with nuget

The same needs to be done for other libraries if this pops up.
